markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
future: true
exclude: [config.ru, Gemfile, Gemfile.lock, LICENSE.txt, Procfile, Rakefile, README.md, vendor]
permalink: pretty
destination: _site/files
defaults:
  -
    scope:
      path: ""
    values:
      rss_link: "/rss.xml"