markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
future: true
exclude: [config.ru, Gemfile, Gemfile.lock, LICENSE.md, Procfile, Rakefile, README.md, vendor]
permalink: pretty
destination: _site/files
gems:
  - jekyll-assets
defaults:
  -
    scope:
      path: ""
    values:
      rss_link: "/rss.xml"
