exclude: [LICENSE.md, README.md]
permalink: pretty
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
collections:
  articles:
    output: true
    permalink: /:path
plugins:
  - jekyll-redirect-from
