# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
markdown: redcarpet

title : Robin
tagline: Thoughts
author :
  name : Robin Winslow
  email : robin@robinwinslow.co.uk
  github : nottrobin
  twitter : nottrobin

production_url : http://nottrobin.github.com

JB :
  # For commented version see https://github.com/plusjade/jekyll-bootstrap/blob/master/_config.yml
  version : 0.2.13
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

  comments :
    provider : disqus
    disqus :
      short_name : jekyllblog
   
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-2993676-7'

  sharing :
    provider : false
