redcarpet:
    extensions: [with_toc_data]
future: true
exclude: [config.ru, Gemfile, Gemfile.lock, LICENSE.md, Procfile, Rakefile, README.md, vendor, env, env3]
permalink: pretty
destination: _site
defaults:
  -
    scope:
      path: ""
    values:
      rss_link: "/rss.xml"
